default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: redesign_development
  username: redesign
  password: <%= ENV['REDESIGN_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: redesign_test
  username: redesign
  password: <%= ENV['REDESIGN_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: redesign_production
  username: redesign
  password: <%= ENV['REDESIGN_DATABASE_PASSWORD'] %>
